services:
  db:
    image: postgres:16  
    environment:
      - POSTGRES_DB=treatment
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=4543
    ports:
      - "5432:5432"
    volumes:
      - ./init-scripts:/docker-entrypoint-initdb.d  
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U postgres"]
      interval: 10s
      timeout: 5s
      retries: 5

  backend:
    build: ./API
    ports:
      - "5000:8080"
    environment:
      - ConnectionStrings__DefaultConnection=Host=db;Port=5432;Database=treatment;Username=postgres;Password=4543
      - ASPNETCORE_ENVIRONMENT=Development
    depends_on:
      db:
        condition: service_healthy

  drug-reference:
    build: ./Parser
    ports:
      - "8000:8080"
    environment:
      - DB_HOST=db
      - DB_PORT=5432
      - DB_NAME=treatment
      - DB_USER=postgres
      - DB_PASSWORD=4543
      - PYTHONUNBUFFERED=1
    depends_on:
      db:
        condition: service_healthy

volumes:
  postgres_data: